### ISSUE TITLE
Problem with checking 4.5.2

### ISSUE THREAD

**Issue by ghost** [ReVolly/NsisDotNetChecker#15]
Invalid command: DotNetChecker::IsDotNet452Installed
Error in macro CheckNetFramework on macroline 58

I have built DLL and it's OK.

**Comment by jeusdi** [comment]
I've the same problem. Is it been solved?

**Comment by raouldc** [comment]
The dll in the bin folder on the Main branch is an older version. You wont get an error if you compile it yourself from the latest src code. Let me know if you cant compile and just want the plugin dll

**Comment by gigazet** [comment]
Can you please make binary for DotNetChecker dll? 
It fails to compile from sources in vs0215.

**Comment by ReVolly** [comment]
@gigazet try now, should be working.
