### ISSUE TITLE
Can't Compile, error because of if-statement in Marco

### ISSUE THREAD

**Issue by F3nr1s** [ReVolly/NsisDotNetChecker#17]
Hi,
this is my first time with NSIS, so I'm a total beginner.

I'm trying to make a Setup-File which checks for .Net 4.0 Full and if not found, installs it. But I get following error (I have removed the username for privacy reasons):

----
Processing config: c:\PROGRA~2\nsis\nsisconf.nsh
Processing script file: "c:/Users/<Username>/DOCUME~1/cius4/src/setup/cius.nsi" (ACP)
Invalid command: ${If}
Error in macro CheckNetFramework on macroline 13
Error in script "c:/Users/<Username>/DOCUME~1/cius4/src/setup/cius.nsi" on line 3 -- aborting creation process

----

If I add "!include LogicLib.nsh" at the beginning of my nsi-File, the error changes to:

----
Processing config: c:\PROGRA~2\nsis\nsisconf.nsh
Processing script file: "c:/Users/<Username>/DOCUME~1/cius4/src/setup/cius.nsi" (ACP)
Error: command StrCmp not valid outside Section or Function
Error in macro _== on macroline 1
Error in macro _If on macroline 9
Error in macro CheckNetFramework on macroline 13
Error in script "c:/Users/<Username>/DOCUME~1/cius4/src/setup/cius.nsi" on line 3 -- aborting creation process

----

So long,

**Comment by bveenvliet** [comment]
Put the !insertmacro inside a Section or Function like it says in the second error message.  Like this.

    Section "Microsoft .Net Framework v4.0 (required)"
       SectionIn RO
       !insertmacro CheckNetFramework 40Full
    SectionEnd
