### ISSUE TITLE
Add .NET 4.6 Support

### ISSUE THREAD

**Issue by BrisingrAerowing** [ReVolly/NsisDotNetChecker#18]
I am using .NET 4.6, and I would like to use this library to check for and install it. I am a complete C/C++ dummy, so I can't do much there. I did try a few weeks ago to get it working, but didn't really get anywhere.

**Comment by grmartin** [comment]
See https://github.com/ProjectHuman/NsisDotNetChecker/pull/20

**Comment by BrisingrAerowing** [comment]
That's exactly what I did. Strange that it didn't work at that time, but it works now? Might have been a Windows 8.1 issue. :confounded:
