### ISSUE TITLE
DotNet 4.5.2 reboot spontaneous

### ISSUE THREAD

**Issue by hummocky** [ReVolly/NsisDotNetChecker#19]
Hi,
I have been using the Nsis DotNetChecker with success for many installers (dotNet 4.0). This is a really nice component - thanks for that.

Recently I added support for dotNet 4.5.2. Subsequently, a number of users have reported that the installer reboot spontaneously during the dotNet 4.5.2 installation. One report say at 20% progress.
After the reboot the application appears to be installed properly.

I have not been able to trigger this scenario my self and my question is therefor:
Have any of you encountered this situation/problem too?
If yes, have you found a proper solution to this side effect?

Thanks in advance.

Best Regards
-Morten

**Comment by hummocky** [comment]
In the DotNetChecker.nsh I will try to change:

ExecWait '$TEMP\dotnetfx.exe /q /c:"install /q"'

to

ExecWait '$TEMP\dotnetfx.exe /q /norestart /c:"install /q"'

Hope this works.

Cheers
-Morten

**Comment by tbnorris** [comment]
I know this was some time ago, but my current pull request for my current fork adds a second macro that delays a restart and returns if an install was performed.
tbnorris/NsisDotNetChecker
