### ISSUE TITLE
Could not download  .NET Framework 4.6.2

### ISSUE THREAD

**Issue by ghost** [ReVolly/NsisDotNetChecker#28]
After Tried to download .NET Framework 4.6.2, below popup is showing.
![image](https://cloud.githubusercontent.com/assets/1751315/20587067/ff1baf7e-b244-11e6-8b8c-e2a6c3bad45f.png)

Then Press 'Yes'. I below error is occured.
![image](https://cloud.githubusercontent.com/assets/1751315/20587062/f061a9d4-b244-11e6-99db-4949a1b78221.png)

**Comment by cstyle** [comment]
That posting was written by me!
